name: Generate Snake Animation ğŸ

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    name: Generate Snake ğŸ
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositÃ³rio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera a cobrinha em SVG e GIF
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: gpaferrari
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Publica no branch "output"
      - name: Deploy to GitHub Pages ğŸš€
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
